server:
  port: 8009
spring:
  application:
    name: service-acl
#数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/author_permission?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.1.43
    port: 6379
    database: 0
    timeout: 1800000
    letture.pool.max-active: 20
    letture:
#    最大阻塞等待时间，负数表示没有限制
      pool.max-wait: -1
#     最小空闲
      pool.min-idle: 0
