server:
  port: 8080
  servlet:
    context-path: /author-service
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/author?useUnicode=true&characterEncoding=utf-8
    username: root
    password: huangzichao520
#  jpa:
#    show-sql: true
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    password: 123456
#    port: 6379
#  thymeleaf:
#    cache: false
#    prefix: /template/
#    suffix: .html
